### ISSUE TITLE
Facebook ads strike back (gathering info)

### ISSUE THREAD

**Issue by kowith337** [kowith337/PersonalFilterListCollection#13]
Expected the Facebook features will evolved in every beginning or the first day of new month, like it's happen to me that...
- **[2018/07/01]** Facebook update **stories** features on mobile sites, even users didn't install their official apps (e.g. visit `m.facebook.com` or `touch.facebook.com`)
- **[2018/08/01]** I've got block to access certain domains (e.g. `mbasic.facebook.com`, `touch.facebook.com` and then redirect to `h.facebook.com` **without using HTTPS for this subdomain**, then sent to `mobile.facebook.com` instead) because they falsely detect some ISP proxy as a mobile network, also any carrier that collaborate with Facebook to offer their `Free Basics` services will prevent access certain subdomains that I've mentioned above and force users to allow the `Free Basics` app to access your account in order to save data cost.
- **[2018/09/01]** some users who use uBlock origin [reported](https://github.com/uBlockOrigin/uAssets/issues/3367) the sponsored posts is now re-appear again, I don't know about the change because I've focused the rules to use on mobile browser first (only Firefox for Android or any forks can install uBO), so I will looking for it if I found one.

**Comment by kowith337** [comment]
I think the first rules `###substream_1:has([id^="feed_subtitle_"]:has-text(Sp))` the `has-text` range is too wide (only just two letters?), is it should be `Sponsored` or not?

But the rules that use `##[id^=hyperfeed_story_id_]` seems to be OK.

**Comment by GetGankNow** [comment]
@kowith337 I don't know to much about rules, but those works.
Ask @mapx- for the first rule.

**Comment by kowith337** [comment]
With my equipped filter (FZK) still cannot see any ads, or because I'm using Facebook Purity along with uBO rules.

If I'm still not see ads, I will switch to another profile to test this out.

**Comment by kowith337** [comment]
This is not a good sign...
6f0ca567fd7a90e73f92765b1d10e11c894ac985

**Comment by kowith337** [comment]
YES! Make it worst and beyond!!
https://www.reddit.com/r/assholedesign/comments/a4qeyo

**Comment by kowith337** [comment]
I think I don't see any ads when open mobile site version (include basic and touch) and also I've tired to create rules for hiding ads on desktop site, I will closing...
