### ISSUE TITLE
Thumbnails don't appear when using it.

### ISSUE THREAD

**Issue by TonySSS100** [kowith337/PersonalFilterListCollection#3]
I have an issue with this script for Gelbooru to hide ads where whenever I use it:
ALL thumbnails won't load anymore and remain stuck with the download text strangely, but it does block all ads there at least surprisingly.
Is it only just me or does others who use it besides me have this problem too perhaps?
I really hope this problem will be fixed asap so that I can enjoy that website I love so much without any annoying ads anymore.

(BTW, I'm using normal uBlock and not Origin version)

**Comment by kowith337** [comment]
- What browser and uBlock version?
- First, try switch to uBlock Origin instead, I don't know about old uBlock devs are they still updated it?
- Somewhat reproducible, If you have any blockers or privacy tools that handle request before uBlock does, like I've installed DuckDuckGo Extension _([AMO](https://addons.mozilla.org/en-GB/firefox/addon/duckduckgo-for-firefox/), [Chrome](https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg))_ along with uBlock, and see all thumbnails stopped loading, the thumbnails will load normally if I've whitelisted in DDG.

Not Whitelisted
![Not Whitelisted](https://user-images.githubusercontent.com/16535467/37396527-bdba3234-27ab-11e8-8705-1739e34a345f.png)

Whitelisted
![Whitelisted](https://user-images.githubusercontent.com/16535467/37396518-b29c15ac-27ab-11e8-9632-b5cff53b809f.png)

**Comment by TonySSS100** [comment]
Well, I actually tried to use it in Origin now instead and it worked, it now shows the thumbnails properly without any ads finally. So basically it only works with that version of uBlock apparently then, you should consider it for the normal version too in the future perhaps if you like. Thanks a lot anyways

**Comment by kowith337** [comment]
Sorry, but I cannot do the backward compatibility due to their ads code is now evolved, my filter is include script injection and CSS modification to foil those holes, that's why it's require uBO or Nano or any forks that regularly follow updates from uBO.
