### ISSUE TITLE
l.facebook.com links immediately closed upon loading

### ISSUE THREAD

**Issue by llacb47** [kowith337/PersonalFilterListCollection#39]
### What type of resource that you're use?
> Filterlist (Facebook Zuckestion Killer)

### Describe the issue
> Line 19 in Facebook Zuckestion Killer breaks Facebook links on l.facebook.com when they automatically open in a new tab (treated as popup).

### Steps to reproduce
1. Visit an event with a link in the description or in the information about the organizer (such as https://www.facebook.com/events/312098952822614/ or https://www.facebook.com/events/1049063085287459/).
2. Click on the link.
3. An l.facebook.com link opens in a new tab and is immediately blocked and closed.
...

### Expected behaviour
> The l.facebook.com page will be strict blocked.

### Actual behaviour
> The l.facebook.com new tab popup is blocked and closed immediately.

### Screenshots
> Not needed

### Logs
> N/A

### Additional notes
> This can be resolved by removing ",popup," from line 19 of the Facebook Zuckestion Killer filter list.

**Comment by kowith337** [comment]
Sorry because I think I'm too paranoid and sensitive about that after they've implement tracking method with `fbclid`

Can you confirm the fix?

**Comment by llacb47** [comment]
Yep, fixed.

**Comment by p1r473** [comment]
This is still blocked @kowith337 if you meant to whitelist it.

**Comment by kowith337** [comment]
I have no deal for whitelisting or removing, this issue is only targeting about cannot open in new browser tab/window

Due to off-Facebook activity that lead me to do that, do you expected that clicking link from `Facebook` will not following you around anyway?

And currently it's closed already.
