### ISSUE TITLE
Facebook Ads Library broken by Zuckestion Killer

### ISSUE THREAD

**Issue by llacb47** [kowith337/PersonalFilterListCollection#41]
### What type of resource that you're use?
> Filterlist (Facebook Zuckestion Killer)

### Describe the issue
> The rule `||facebook.com/ads/$all,~document` breaks the [Facebook Ad Library](https://www.facebook.com/ads/library/)

### Steps to reproduce
1.  Visit the [Facebook Ad Library](https://www.facebook.com/ads/library/)

### Expected behaviour
> The webpage displays and is usable

### Actual behaviour
> Total breakage because of the rule `||facebook.com/ads/$all,~document`

### Screenshots
> Not needed

### Logs
| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 | \|\|facebook.com/ads/$inline-font | -- | `www.facebook.com` | 1 | inline-font | `https://www.facebook.com/ads/library/` |
| +1 | \|\|facebook.com/ads/$inline-script | -- | `www.facebook.com` | 1 | inline-script | `https://www.facebook.com/ads/library/` |
| +1 |  |  | `www.facebook.com` | 3 | image | `https://static.xx.fbcdn.net/rsrc.php/yo/r/iRmz9lCMBD2.ico` |
| +1 |  |  | `www.facebook.com` | 1 | other | `https://www.facebook.com/data/manifest/` |
| +0 |  |  | `www.facebook.com` | 3 | image | `https://static.xx.fbcdn.net/rsrc.php/v3/yJ/r/Atcx8WVmhII.png` |
| +0 | `@@\|\|www.facebook.com/ads/$generichide` | ++ | `www.facebook.com` | 1 | generichide | `https://www.facebook.com/ads/library/` |
| +0 |  |  | `www.facebook.com` | 3 | script | `https://static.xx.fbcdn.net/rsrc.php/v3/y6/r/WOK3yQMb5Q2.js` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yP/l/0,cross/UWvelHu-ARZ.css` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yY/l/0,cross/DUpxbZ0vki3.css` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/ya/l/0,cross/4x2W71TdmOt.css` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yU/l/0,cross/oIj6-We8_fy.css` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yM/l/0,cross/C3hU9DlWOse.css` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yV/l/0,cross/xK7xBKHFFrv.css` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/ym/l/0,cross/jUNpBsn4UrM.css` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yp/l/0,cross/f4ziW9qTGPY.css` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yZ/l/0,cross/SgsHkQJxU6a.css` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yH/l/0,cross/NOKwdHAT7x9.css` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yB/l/0,cross/tSQrV5CwomX.css` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yY/l/0,cross/5P2awCyn6kq.css` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yp/l/0,cross/XGS15S4Lf3t.css` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yx/l/0,cross/VOTjxaoKpYj.css` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yw/l/0,cross/e88Qm9EHd9z.css` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yC/l/0,cross/o7MAb-mcGwh.css` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yB/l/0,cross/QXecUxd0oJs.css` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yC/l/0,cross/Vd8BYNcvrmT.css` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yS/l/0,cross/yAMRaqiSB6h.css` |
| +0 |  |  | `www.facebook.com` | 3 | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yy/l/0,cross/bmEueVJWMU6.css` |
| +0 | \|\|facebook.com/ads/$inline-font | -- | `www.facebook.com` | 1 | inline-font | `https://www.facebook.com/ads/library/` |
| +0 |  |  | `www.facebook.com` | 1 | doc | `https://www.facebook.com/ads/library/` |

### Additional notes
> Add the rule `@@||facebook.com/ads/library/*$all,first-party` or similar

**Comment by kowith337** [comment]
No affect to XUL, your whitelist is worked!

Test with...
- NanoAdblocker1.0.0.120
- Cent Browser 4.0.9.112 (based on Chromium 74.0.3729.169)

Updating within next commit.

**Comment by kowith337** [comment]
Wait, still not work!

**Comment by kowith337** [comment]
It's still have problem if put the whitelist like...

`@@||facebook.com/ads/library/$...` or `@@||facebook.com/ads/library/*$...`

will be still stuck by blocking rule if you're visiting that page while remove the slash behind `library` word, so I've added whitelist rules without slash and wildcard to make sure it's whitelisted properly.

**Comment by llacb47** [comment]
Should work now
