### ISSUE TITLE
Menu bar doesn't divide properly

### ISSUE THREAD

**Issue by kowith337** [kowith337/PersonalFilterListCollection#49]
### What type of resource that you're use?
GelboLube Filterlist

### Describe the issue
Menu bar broken, normally it should divide each side.

### Steps to reproduce
1. Go to Gelbooru (on mobile device via Firefox Android and/or related)
 - Optional to reproduce from desktop, just snap to specific side and make sure browser window are have half of screen size, or `width` of browser window are less than `768`.
2. Search something
3. Look at header menu

### Expected behaviour
Menu bar should divide properly with half width for each-side.

### Actual behaviour
Menu bar doesn't divide properly, especially left side.

### Screenshots
![image](https://user-images.githubusercontent.com/16535467/68539847-366bf080-03bc-11ea-9e93-ba2f8ff8bf22.png)

### Logs
None

### Additional notes
None, yet.

**Comment by Jorge9811** [comment]
> Menu bar doesn't divide properly

![firefox-2020-01-03_12-03-57](https://user-images.githubusercontent.com/54429803/71730629-78943a00-2e21-11ea-8029-db20fc41efa6.png)

**Comment by kowith337** [comment]
I idn't touch and/or fix that yet due to they add more and more items in second menu (black bar), I may thinking about...
- Remove CSS rules that use to divide those two menu bars, or...
- Remove some menu items that not necessary much to save space.

**Comment by kowith337** [comment]
Can you give me feedback about new adjustment?
`https://github.com/kowith337/PersonalFilterListCollection/raw/master/filterlist/testing/GelboLube-NonProd.txt`

**Comment by Jorge9811** [comment]
> Can you give me feedback about new adjustment?
> 
> `https://github.com/kowith337/PersonalFilterListCollection/raw/master/filterlist/testing/GelboLube-NonProd.txt`

I know I'm like super late, but I just tried it out and it seems to be working correctly overall.
The page looks clean and the menu bar doesn't look wrong anymore.
![gelbolubetest](https://user-images.githubusercontent.com/54429803/75706165-81777f80-5c9b-11ea-9236-9fa9bac9a8f6.png)

**Comment by ViperAcidZX** [comment]
I'm having this problem again.
