### ISSUE TITLE
False positive: chromesyncpasswords-pa.googleapis.com

### ISSUE THREAD

**Issue by p1r473** [kowith337/PersonalFilterListCollection#51]
### What type of resource that you're use?
Hosts file

### Describe the issue
chromesyncpasswords-pa.googleapis.com is blocking Chrome password sync

### Steps to reproduce
1. Use your personal filter list
2. Chrome password sync broken
...

### Expected behaviour
Chrome password sync works

### Actual behaviour
Chrome password sync does not work

**Comment by kowith337** [comment]
I have no deal with `Chrome` and I've found out that domain still trying to connected while I'm using pDNSF, even I've disabled `Chrome` already.

Even I use `Chrome` at desktop computer and need to sync my settings, the passwords or credentials is my first thing to shut it off!

**Comment by p1r473** [comment]
Okay, thank you
