### ISSUE TITLE
redirector.googlevideo.com

### ISSUE THREAD

**Issue by p1r473** [kowith337/PersonalFilterListCollection#54]
Hi,
I believe this domain is a false positive.
Blocking this domain breaks Google Play Movies.
I have whitelisted on my end, but you might want to remove from your blocklist.

**Comment by kowith337** [comment]
I often see this domain attempts to connect, even use NewPipe, SkyTube, etc.
> Rarely to see for generic videos, but may often see it's attempt if play some videos that contains other claims.
And again, not my interest to use much kind of any services from `Google`

**Comment by kowith337** [comment]
Oh, and I randomly found in SkyTube that it show some error about attempt to connecting this domain, the error dialog also reveal that it's contain `ei` parameter, it's the same thing that Google search binding in everytime you make search from website omnibox (Not browser address bar).
So, any better reason to allow that things, if not, I will lockdown later.

`kthxbye`
