### ISSUE TITLE
firebaseinstallations.googleapis.com

### ISSUE THREAD

**Issue by p1r473** [kowith337/PersonalFilterListCollection#58]
This domain breaks Google apps that utilize Firebase such as https://ncov2019.live/map
I have whitelisted on my end but just alerting you FYI.

**Comment by llacb47** [comment]
I don't see any firebase at that link

**Comment by p1r473** [comment]
Possiblw they changed their tech stack, but https://ncov2019.live/map used Firebase Live Data and map would not load unless I unblocked it
Either way, I have whitelisted it on my end.
```
Firebase is Google's mobile platform that helps you quickly develop high-quality apps and grow your business.
```
Not sure why you want to block a Google app platform, but that's your choice!
