### ISSUE TITLE
content-autofill.googleapis.com

### ISSUE THREAD

**Issue by p1r473** [kowith337/PersonalFilterListCollection#59]
Hi,
This is breaking Google Chrome's autofill
I have whitelisted on my end but just alerting you FYI.

**Comment by kowith337** [comment]
Explanation only in this issue.

1. I didn't use AutoFill, not just Chrome, but all of any browsers!
2. Even I've disable Google app, include Chrome, I still see popup that suggest to remember passwords (Android 10), and that's remind me to disable AutoFill service in Android settings!!
> Even I didn't have any clue that it's attempt to connecting to that host or not, but still block it anyway.
