### ISSUE TITLE
getpocket.cdn.mozilla.net

### ISSUE THREAD

**Issue by p1r473** [kowith337/PersonalFilterListCollection#60]
Hi Kowith,
I believe this to be a false positive
Pocket is a news reading browser extension where you can save  articles to read for later
They recently got incorporated right into FireFox
This domain is the CDN (Content Delivery Network) for it, which hosts many static assets.

Thanks!

**Comment by kowith337** [comment]
1. It's probably shift with in-browser snippets.
2. I think "Web browser" is mean for browse the web as you want, not the news feed reader.
  > If you want that, find RSS app and feed links to subscribe with separate clients.
3. It's already in aggressive list, that's mean this issue will be ignored, no matter what.
