### ISSUE TITLE
Banner ad on gelbooru.com results page

### ISSUE THREAD

**Issue by twocows** [kowith337/PersonalFilterListCollection#66]
### What type of resource that you're use?
GelboLube \(Universal\) \[stack menubar modified\]
Version: 202008042032

### Describe the issue
Ads get through on search results

### Steps to reproduce
1. Search for something
2. Banner ad appears at the top of results

### Expected behaviour
No banner ads

### Actual behaviour
Banner ad on results page

### Screenshots
Attached
![screenshot](https://user-images.githubusercontent.com/6536741/98067824-69f32680-1e28-11eb-9b08-e52a85e86701.jpg)

### Logs
N/A

### Additional notes
Firefox-ESR 78.4.0, Win10-2004-x64. Other addons and filterlists (e.g. EasyList) are active, I can start selectively disabling stuff if you're unable to reproduce.

**Comment by kowith337** [comment]
I've reproduced on Waterfox Current with subscribe only Gelbolube List and found it's re-promoted TheDoujin, now I've updated filterlist to hide that.
Hope the filters work fine.

**Comment by twocows** [comment]
Looks good, thank you!
