### ISSUE TITLE
A typo in a domain name

### ISSUE THREAD

**Issue by j-moriarti** [kowith337/PersonalFilterListCollection#70]
### What type of resource that you're use?

domains/pdnsf-additionalhosts.txt
### Describe the issue

there is an small typo at domain ending [Here](https://github.com/kowith337/PersonalFilterListCollection/blob/7f11042b36a097b902572fe0dcb3448b10915cbb/domains/pdnsf-additionalhosts.txt#L338)
### Steps to reproduce
...

### Expected behaviour

the domain should be `clientmetrics-pa.googleapis.com`
### Actual behaviour

there is no **.com** TLD in `clientmetrics-pa.googleapis.`
### Additional notes

Nice work! Thanks :+1:

**Comment by kowith337** [comment]
Thanks for reporting, I didn't noticed that I need to add TLD, probably myself copy/paste issue.
