### ISSUE TITLE
Make use of removeparam syntax instead of complete blocking to remove tracking parameters on the fly.

### ISSUE THREAD

**Issue by Rtizer-9** [kowith337/PersonalFilterListCollection#72]
### What type of resource that you're use?
Zuckestion Killer and Chat awareness filterlists

### Describe the issue
Urls which have fbclid and such parameters takes you through an intermediate page where you have to click on the filtered link without parameters. If I'm correct this intermediate page can be easily avoided by using the `removeparam` syntax as described here [https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#removeparam](url)

### Steps to reproduce
1. Click any url containing fbclid parameter. You'll be presented with an intermediate page as mentioned above already.

### Additional notes
Substituting  `removeparam` syntax in the filterlist in appropriate places instead of completely blocking urls can speed up things since now the syntax is available so tracking parameters can be removed on the fly which will lead the user directly to the page instead of an intermediate page.

**Comment by Rtizer-9** [comment]
After creating this issue I read #19 and I think that even if you don't want to use 'removeparam' for all parameters, it can atleast be used for fbclid which can speed things up.

**Comment by kowith337** [comment]
Updated in last week to only `removeparam` and not completely block URLs that contains its parameter for...
- `fbclid`
- `/flx/` navigation warning that done by `Facebook`

However, I may not unblock uBO warning page if navigating through `l.` or `lm.` because going into those subdomains mean *probably* letting `Facebook` read outgoing URLs and still wrapping more parameters, include `fbclid`
> Like `Google` does when you click tracking links in search results that turn out it going to `/url?` first before sent users to actual sites.

**Comment by Rtizer-9** [comment]
Extensions like ClearUrls handle the `l.` and `lm.` redirections pretty well so the only problem I was facing was with links containing `fbclid`. 

Thanks for implementing the commit so quickly.
