### ISSUE TITLE
Automate redirect on Facebook Zuckestion Killer - Base

### ISSUE THREAD

**Issue by thiendt2k1** [kowith337/PersonalFilterListCollection#78]
### What type of resource that you're use?
Filter list, in ublock origin

### Describe the issue
Whenever i click into the link on facebook, they are blocked, which i appreciate, but is there any way or trick that get the job done automatically, without me having to click onto the u section of the link(preferentially, not install another extension, script could be acceptable)

### Steps to reproduce
1. Click some links on facebook
2. Block screen pop up on ublock
3. click onto U section to redirect
4. 
...

### Expected behaviour
Not need to click anything

### Screenshots

![image](https://user-images.githubusercontent.com/58879301/231372415-97dae715-09b3-4a90-894a-57c431f3e63e.png)

**Comment by kowith337** [comment]
I'm afraid to say that I won't do it, you can read my reply in past related issue here about why...
https://github.com/kowith337/PersonalFilterListCollection/issues/72#issuecomment-883304370
