### ISSUE TITLE
nordvpn.com

### ISSUE THREAD

**Issue by p1r473** [kowith337/PersonalFilterListCollection#80]
### What type of resource that you're use?
hosts file

### Describe the issue
nordvpn.com popular vpn client 

### Steps to reproduce
1. 
2. 
3. 
4. 
...

### Expected behaviour
whitelisted

### Actual behaviour
false positive

### Additional notes
on /hosts/hosts_leftover.txt

**Comment by kowith337** [comment]
I'm sorry, due to somewhat shdy promotion, I won't remove out of my list.
