### ISSUE TITLE
detectportal.firefox.com

### ISSUE THREAD

**Issue by p1r473** [kowith337/PersonalFilterListCollection#81]
### What type of resource that you're use?
 - https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/hosts/hosts_leftover_aggressive.txt
 - https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/hosts/hosts_leftover.txt
 - 
### Describe the issue
Firefox domain to detect captive portals

**Comment by kowith337** [comment]
As far as I know for now...

1. There's no advantage or disadvantage about allowing web browser to check connectivity that it's currently have internet or not.
2. Some forks of Firefox, include custom prefs (e.g. user.js, policy config, etc.) are mostly patched that by "disable captive portal", that's mean blocking that domain are no true effects for it.
3. You've cut out almost of issue template, I'll considered to ignore at first.
